apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      secretKeyRef:
        name: key-vault-name-secret-name
        key: key-vault-name-secret-key
    - name: spnTenantId
      secretKeyRef:
        name: service-principal-tenant-id-secret-name
        key: service-principal-tenant-id-secret-key
    - name: spnClientId
      secretKeyRef:
        name: service-principal-app-id-secret-name
        key: service-principal-app-id-secret-key
    - name: spnCertificate
      secretKeyRef:
        name: service-principal-certificate-secret-name
        key: service-principal-certificate-secret-key
auth:
  secretStore: kubernetes